services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db_anicet
      POSTGRES_USER: azegha
      POSTGRES_PASSWORD: azegha2002#
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://azegha:azegha2002#@db:5432/db_anicet

volumes:
  postgres_db:
